# 行列演算の基礎

$\boldsymbol{w}=(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^T\boldsymbol{y}$

この計算を行うためには、何ができないといけないのか？
- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [18]:
import numpy as np

In [19]:
#  ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [20]:
# 行列の定義 （大文字にしておくとわかりやすい)
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [21]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [22]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [27]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [28]:
#↑ [[1,0], [0, 1]] と同等

# よくある間違い

In [45]:
# ベクトルの定義で、二重括弧にしない。→転置をとったときに、うまく転置されない
x = np.array([1,2,3])
print(x) # 一見問題ないが
x.T #転置をとってもかわらない


[1 2 3]


array([1, 2, 3])

In [44]:
x = np.array([[1,2,3]]) #二重括弧にすると
x.T # うまく転置される

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理


In [46]:
X

array([[1, 2],
       [3, 4]])

In [48]:
X.shape # shapeで行と列のサイズが取れる

(2, 2)

In [50]:
X = np.array([
    [2,3,4],
    [1,2,3]
])


array([[2, 3, 4],
       [1, 2, 3]])

In [51]:
X.shape

(2, 3)

In [52]:
row, col = X.shape

In [53]:
row

2

In [55]:
col

3

In [58]:
#各行ごとの処理はforがつかえる
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


# 演習問題

$\boldsymbol{X} = \left[
    \begin{array}{rrr}
     1 & 2 & 3 \\
      1 & 2 & 5 \\
      1 & 3 & 4 \\
      1 & 5 & 9 \\
    \end{array}
  \right], 
  \boldsymbol{y} = \left[
    \begin{array}{r}
     1 \\
     5 \\
     6 \\
     8 \\
    \end{array}
  \right]のとき
  $
  
  $\boldsymbol{w}=(\boldsymbol{X}^TX)^{-1}\boldsymbol{X}^Ty$

In [63]:
# ↑Xは４サンプル、変数は２個（一番左の１はダミー変数）、yは１変数である

- Step1: $\boldsymbol{X}^TX$
- Step2: $(\boldsymbol{X}^TX)^{-1}$
- Step3: $\boldsymbol{X}^Ty$
- Step4: $\boldsymbol{w}=(\boldsymbol{X}^TX)^{-1}\boldsymbol{X}^Ty$

In [68]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [70]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
y

array([[1],
       [5],
       [6],
       [8]])

In [72]:
# Step1
XtX = np.dot(X.T, X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [74]:
# Step2
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [77]:
# Step3
Xty = np.dot(X.T, y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [80]:
# Step4
w =np.dot(XtX_inv, Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# Scikit-learnで実装

In [ ]:
# import sklearn

In [85]:
#重回帰分析のみ読み込み メモリ節約のため
from sklearn.linear_model import LinearRegression

In [87]:
# モデルの宣言
model = LinearRegression()
# モデルの学習　←モデルの学習とは、パラメータの調整のこと
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [88]:
# 調整後のパラメータ numpyのStep4
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [89]:
model.intercept_ # numpyのStep4の1の値

array([-0.14285714])

In [92]:
# Scikit-learnはわざわざ１を入れなくても、intercept_として内でうまく分離してくれる
# 分離したくない場合は、model=LinearRegression(fit_intercept=False)とすると、
# coef_に1の値(-0.14285714)が入り、intercept_ に0が入るようになる

In [94]:
# 予測精度は？ ←決定係数と呼ぶ　0だと論外、1だとすごく良い. 0.7くらいあれば完璧ではないが、悪くない

In [95]:
model.score(X,y)

0.6923076923076926

In [96]:
# 予測値の計算
x = np.array([[1,2,3]]) # query

In [98]:
y_pred = model.predict(x)
y_pred

array([[3.]])