## 単回帰分析
傾きaを求める式
$$
\begin{align}
a=\frac{\sum_{n=1}^{N}x_ny_n}{\sum_{n=1}^{N}x_n^2}
\end{align}
$$

サンプルデータ

|x|y|
|---|---|
|1|2|
|2|3.9|
|3|6.1|


### numpyの使いかた

In [6]:
import numpy as np

In [7]:
# ベクトルの定義
x = np.array([1,2,3])

In [8]:
x

array([1, 2, 3])

In [10]:
y = np.array([2,3.9,6.1])
y

array([2. , 3.9, 6.1])

In [11]:
#データの中心化
#平均の算出
x.mean()

2.0

In [12]:
y.mean()

4.0

In [13]:
#中心化
xc = x - x.mean()
xc

array([-1.,  0.,  1.])

In [14]:
yc = y - y.mean()
yc

array([-2. , -0.1,  2.1])

In [15]:
# パラメータaの計算

In [22]:
# 要素ごとの掛け算（要素積）
xx = xc * xc

In [23]:
xy = xc * yc

In [24]:
xx.sum()

2.0

In [25]:
xy.sum()

4.1

In [26]:
a = xy.sum()/xx.sum()
a

2.05